### PR TITLE
small formatting fixes

### PR DESCRIPTION
**Pull request by mpmc**
As title :)

### CODE REVIEW

**Comment by RoEdAl** [comment]
`has%s channel` is a valid formatting pattern.

It is converted to `has channel` or `hasn't channel`.
After your modifications: `has ""` or `has "n't"`!

**Comment by mpmc** [comment]
Ah, so it is what I originally thought! 

When I first saw it, I thought "hasn't channel"/"has not channel" doesn't sound right so it must be something else, went with the safe option of assuming it meant the channel was in a mode of some sort (thinking, t, e, here). I guessed wrong, I'll change it again!

**Comment by RoEdAl** [comment]
There are many many more messages with bad English.

For me instead of `has`/`doesn't have` a better solution is just `channel:on`/`channel:off` or maybe `channel:attached`/`channel:detached`.

In `src/channel.c` there's similar line:

```c
ast_debug(1, "[%s] Call - idx:%d mpty:%d, [%s] -> [%s] has%s channel\n", PVT_ID(pvt), call_idx, CPVT_TEST_FLAG(cpvt, CALL_FLAG_MULTIPARTY) ? 1 : 0, call_state2str(oldstate), call_state2str(newstate), channel ? "" : "'t");
```

Could you correct this line too? Here with changed order:

```c
"[%s] Call - idx:%d mpty:%d channel:%s [%s] -> [%s]\n"
```

**Comment by RoEdAl** [comment]
Fixed in 5c5f074541925325e4d441254b787016c6e65521.
Thanks.

**Pull request closed without merging**
